repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-illegal-windows-names
      - id: check-merge-conflict
      - id: destroyed-symlinks
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1 # keep this in sync with pyproject.toml
    hooks:
      - id: ruff-check
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0 # keep this in sync with pyproject.toml
    hooks:
      - id: black
