name: Run tests on all supported Python versions

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.12", "3.13", "3.14" ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install the package and test deps
        run: |
          python -m pip install --upgrade pip setuptools build wheel
          pip install .[test]

      - name: Run pytest
        run: |
          pytest --exitfirst --quiet
